# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  require 'yaml'
  secrets = YAML.load_file('secrets.yml')

  config.vm.define "leader" do |leader|

	leader.vm.provider :digital_ocean do |provider, override|
		override.ssh.private_key_path = '~/.ssh/id_rsa'
		override.vm.box = 'digital_ocean'
		override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digitalocean.box"

		provider.token = secrets['digital_ocean']['secret_token']
		provider.image = 'ubuntu-16-04-x64'
		provider.region = 'nyc3'
		provider.size = '1gb'
	end

  end # end define for "leader" droplet

end
