# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  require 'yaml'
  secrets = YAML.load_file('../secrets.yml')

  config.vm.define "manager", primary: true do |leader|

	leader.vm.provider :digital_ocean do |provider, override|
		override.ssh.private_key_path = '~/.ssh/id_rsa'
		override.vm.box = 'digital_ocean'
		override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digitalocean.box"

		provider.private_networking = true
		provider.token = secrets['digital_ocean']['secret_token']
		provider.image = 'ubuntu-16-04-x64'
		provider.region = 'nyc3'
		provider.size = '1gb'
	end

	leader.vm.provision "shell",
	  path: "../.provision/scripts/swarm-init.sh",
	  privileged: true

  end # end define for "leader" droplet


  config.vm.define "worker-a", autostart: false do |a|
	a.vm.provider :digital_ocean do |provider, override|
		override.ssh.private_key_path = '~/.ssh/id_rsa'
		override.vm.box = 'digital_ocean'
		override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digitalocean.box"

		provider.private_networking = true
		provider.token = secrets['digital_ocean']['secret_token']
		provider.image = 'ubuntu-16-04-x64'
		provider.region = 'nyc3'
		provider.size = '1gb'
	end

	if File.exist?("./secrets/swarm-join.sh")
		a.vm.provision "shell",
	  	  path: "./secrets/swarm-join.sh",
	      privileged: true
	end

  end #end: worker-a


  config.vm.define "worker-b", autostart: false do |b|
	b.vm.provider :digital_ocean do |provider, override|
		override.ssh.private_key_path = '~/.ssh/id_rsa'
		override.vm.box = 'digital_ocean'
		override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digitalocean.box"

		provider.private_networking = true
		provider.token = secrets['digital_ocean']['secret_token']
		provider.image = 'ubuntu-16-04-x64'
		provider.region = 'nyc3'
		provider.size = '1gb'
	end

	if File.exist?("./secrets/swarm-join.sh")
		b.vm.provision "shell",
	  	  path: "./secrets/swarm-join.sh",
	      privileged: true
	end
  end # end: worker-b

  config.vm.provision "shell",
    path: "../.provision/scripts/install-docker.sh",
	privileged: true
end
